; hierarchy dependent
; NH
; _dm31NH_   = 2.534e-15;
; _theta23NH_= 0.831;
; IH
; _dm31IH_   = -2.46e-15;
; _theta23IH_= 0.824;

[Ini]

dm31    = 2.534e-15
theta23 = 0.831


dm21    = 7.530e-17
theta12 = 0.587
theta13 = 0.148


; evolve in adiabatic approximation (0) or the full system (1)
vs = 1


; evolve (1) znu, zg or not (0)
zon = 1


filename    = results
progressbar = yes


; param: {0,1,2} = {\xi, \tilde{\xi}, \Delta n_\alpha} input
param   = 0

xi1= 0.1
xi2= 0.2
xi3= 0.3

xit1 = 0.1
xit2 = 0.2
xit3 = 0.3

dn1  = 0.1
dn2  = 0.2
dn3  = 0.3


Tend    = 1.5
